In [1]:
import pandas as pd

In [8]:
import numpy as np

In [2]:
dataset = pd.read_excel("age_salary.xlsx")

In [3]:
print(dataset)

    Index  Years  Experience   Age  Salary
0       0      1         1.1  21.0   39343
1       1      2         1.3  21.5   39343
2       2      3         1.5  21.0   39343
3       3      4         2.0  21.5   39343
4       4      5         2.2  21.0   39343
5       5      6         2.9  21.5   39343
6       6      7         3.0  21.0   39343
7       7      8         3.2  21.5   39343
8       8      9         1.1  21.0   39343
9       9     10         1.3  21.5   39343
10     10     11         1.5  21.0   39343
11     11     12         2.0  21.5   39343
12     12     13         2.2  21.0   39343
13     13     14         2.9  21.5   39343
14     14     15         3.0  21.0   39343
15     15     16         3.2  21.5   39343
16     16     17         3.0  21.0   39343


In [4]:
dataset=dataset.iloc[:,:-1].values

In [5]:
print(dataset)

[[ 0.   1.   1.1 21. ]
 [ 1.   2.   1.3 21.5]
 [ 2.   3.   1.5 21. ]
 [ 3.   4.   2.  21.5]
 [ 4.   5.   2.2 21. ]
 [ 5.   6.   2.9 21.5]
 [ 6.   7.   3.  21. ]
 [ 7.   8.   3.2 21.5]
 [ 8.   9.   1.1 21. ]
 [ 9.  10.   1.3 21.5]
 [10.  11.   1.5 21. ]
 [11.  12.   2.  21.5]
 [12.  13.   2.2 21. ]
 [13.  14.   2.9 21.5]
 [14.  15.   3.  21. ]
 [15.  16.   3.2 21.5]
 [16.  17.   3.  21. ]]


In [10]:
import numpy as np
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan,strategy="mean")
x=imp.fit_transform(dataset)
print(dataset)

[[ 0.   1.   1.1 21. ]
 [ 1.   2.   1.3 21.5]
 [ 2.   3.   1.5 21. ]
 [ 3.   4.   2.  21.5]
 [ 4.   5.   2.2 21. ]
 [ 5.   6.   2.9 21.5]
 [ 6.   7.   3.  21. ]
 [ 7.   8.   3.2 21.5]
 [ 8.   9.   1.1 21. ]
 [ 9.  10.   1.3 21.5]
 [10.  11.   1.5 21. ]
 [11.  12.   2.  21.5]
 [12.  13.   2.2 21. ]
 [13.  14.   2.9 21.5]
 [14.  15.   3.  21. ]
 [15.  16.   3.2 21.5]
 [16.  17.   3.  21. ]]
